// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqqYaLyiFdqmtTzPmDh6UOgqgn1wq-rro',
    appId: '1:589014447103:web:47300b220f445f8d9d2dca',
    messagingSenderId: '589014447103',
    projectId: 'emvigo-3fab3',
    authDomain: 'emvigo-3fab3.firebaseapp.com',
    storageBucket: 'emvigo-3fab3.firebasestorage.app',
    measurementId: 'G-S2PVT8VWVQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtlhm6bGz-BrK9-azl0RsgkNCQz4FQhZM',
    appId: '1:589014447103:android:e5b22aea2e293cde9d2dca',
    messagingSenderId: '589014447103',
    projectId: 'emvigo-3fab3',
    storageBucket: 'emvigo-3fab3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5K_u5AtPAf2u2vAFDyBSEK1_F9wxDvCg',
    appId: '1:589014447103:ios:d8a472f03ffb822f9d2dca',
    messagingSenderId: '589014447103',
    projectId: 'emvigo-3fab3',
    storageBucket: 'emvigo-3fab3.firebasestorage.app',
    iosBundleId: 'com.example.emvigoMachineTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5K_u5AtPAf2u2vAFDyBSEK1_F9wxDvCg',
    appId: '1:589014447103:ios:d8a472f03ffb822f9d2dca',
    messagingSenderId: '589014447103',
    projectId: 'emvigo-3fab3',
    storageBucket: 'emvigo-3fab3.firebasestorage.app',
    iosBundleId: 'com.example.emvigoMachineTask',
  );
}
